name = "MRICoordinates"
uuid = "3b8319e5-e262-4cb7-99a1-6c5370fe4937"
authors = ["Felix Horger <felix.horger@kcl.ac.uk>"]
version = "0.1.0"

[deps]
HomogeneousCoordinates = "47771e7b-e0bf-483c-9843-56ba79ba06f9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
